
# specify a fully qualified proxy home url, for example, http://10.0.2.2:8080
proxy_home:           'http://10.0.2.2:8080'

# specify api key string received from NASA
nasa_api_key:         'NASA_API_KEY_VALUE'

# specify approov token secret as a base64 string extracted from approov demo 
approov_token_secret: 'APPROOV_TOKEN_SECRET_VALUE'

# specifiy location of approov android library (approov.aar) extracted from approov demo
approov_android_lib:  '../../demo/libraries/android/approov.aar'

#                       0 1 2 3
# 
# config.xml
#   api_url             x x x x
# secrets.xml
#   api_key               x 
# approov.aar                 x
# 
#                       0   2 3 4
# 
# config.js
#   proxy_port          x   x x x
#   nasa_host           x   x x x
#   nasa_protocol       x   x x x 
#   approov_header            x x
#   approov_enforcement       x x
# secrets.js
#   nasa_api_key            x x x
#   approov_token_secret      x x
