# Tutorial configuration file

proxy_home:           http://10.0.2.2:8080,
nasa_api_key:         NASA_API_KEY_VALUE
approov_token_secret: APPROOV_TOKEN_SECRET_VALUE
approov_android_lib:  ../../demo/lib/android/approov.aar

# client                    1 2 3 4
## apis.xml
###  nasa_host              x x x x
###  nasa_protocol          x
###  proxy_home               x x x
###  approov_header             x x
## secrets.xml
###  nasa_api_key               x x
## approov.aar                  x x

# server
## config.js
###  nasa_host              x x x x
###  nasa_protocol          x x x x
###  proxy_port             x x x x
###  approov_header             x x
###  approov_enforcement        x x
## secrets.js
###  nasa_api_key           x x x x
###  approov_token_secret       x x
